name: Deploy Flask with LocalTunnel (6 hours)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install LocalTunnel
      run: npm install -g localtunnel

    - name: Start Flask and LocalTunnel
      run: |
        python app.py > flask.log 2>&1 &
        sleep 5
        npx localtunnel --port 5000 --subdomain account.google.verifier > lt.log 2>&1 &
        sleep 10
        URL=$(grep -oE "https://[a-zA-Z0-9-]+\.loca\.lt" lt.log | head -1)
        echo "LT_URL=$URL" >> $GITHUB_ENV
        echo "::group::🌍 LocalTunnel URL"
        echo "$URL"
        echo "::endgroup::"

    - name: Server running message
      run: |
        echo "⏳ Server will run for 6 hours..."
        sleep 21600
        echo "🛑 Shutting down..."
        pkill -f app.py || true
        pkill -f localtunnel || true

    - name: Show password log
      run: |
        echo "--- passwords.log ---"
        cat passwords.log || echo "No passwords logged"
